
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservice-config-wigger-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservice-config-wigger-dev
#保存为utf-8格式