server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8367/eureka #测试不使用eureka集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept
  prefix: /wigger  #配置统一前缀
  ignored-services: "*" #屏蔽原有访问路径，只能通过网关路由进行访问
  routes:
    mydept.serviceId: microservice-dept # 真是的路由访问的微服务
    mydept.path: /mydept/** #路由

info:
  app.name: wigger_microservice
  company.name: www.wigger.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$






